import { signal } from '@angular/core';
import { v4 as uuidv4 } from 'uuid';

export const accountSumSignal = signal(70000);

export const mockData: any = [
  {
    id: uuidv4(),
    campaignName: 'Summer Sale Campaign',
    status: 'ON',
    keywords: ['summer', 'sale', 'discount', 'clothing'],
    bidAmount: 13,
    campaignFund: 10000,
    town: 'Kraków',
    radius: 50,
  },
  {
    id: uuidv4(),
    campaignName: 'New Year Promo',
    status: 'OFF',
    keywords: ['new year', 'promo', 'celebration', 'sale'],
    bidAmount: 1,
    campaignFund: 5000,
    town: 'Warsaw',
    radius: 30,
  },
  {
    id: uuidv4(),
    campaignName: 'Holiday Special',
    status: 'OFF',
    keywords: ['holiday', 'special', 'discount', 'travel'],
    bidAmount: 2,
    campaignFund: 15000,
    town: 'Gdańsk',
    radius: 100,
  },
  {
    id: uuidv4(),
    campaignName: 'Winter Gear Promo',
    status: 'ON',
    keywords: ['winter', 'gear', 'clothing', 'sale'],
    bidAmount: 6,
    campaignFund: 6000,
    town: 'Wrocław',
    radius: 20,
  },
  {
    id: uuidv4(),
    campaignName: 'Tech Gadgets Sale',
    status: 'ON',
    keywords: ['tech', 'gadgets', 'electronics', 'sale'],
    bidAmount: 22,
    campaignFund: 12000,
    town: 'Poznań',
    radius: 40,
  },
  {
    id: uuidv4(),
    campaignName: 'Back to School',
    status: 'ON',
    keywords: ['school', 'stationery', 'back to school', 'discount'],
    bidAmount: 1,
    campaignFund: 8000,
    town: 'Lublin',
    radius: 60,
  },
  {
    id: uuidv4(),
    campaignName: 'Spring Collection Launch',
    status: 'OFF',
    keywords: ['spring', 'collection', 'fashion', 'launch'],
    bidAmount: 2,
    campaignFund: 11000,
    town: 'Szczecin',
    radius: 70,
  },
  {
    id: uuidv4(),
    campaignName: 'Summer Sale Campaign',
    status: 'OFF',
    keywords: ['summer', 'sale', 'discount', 'clothing'],
    bidAmount: 6,
    campaignFund: 10000,
    town: 'Kraków',
    radius: 50,
  },
  {
    id: uuidv4(),
    campaignName: 'New Year Promo',
    status: 'OFF',
    keywords: ['new year', 'promo', 'celebration', 'sale'],
    bidAmount: 3,
    campaignFund: 5000,
    town: 'Warsaw',
    radius: 30,
  },
  {
    id: uuidv4(),
    campaignName: 'Holiday Special',
    status: 'ON',
    keywords: ['holiday', 'special', 'discount', 'travel'],
    bidAmount: 3,
    campaignFund: 15000,
    town: 'Gdańsk',
    radius: 100,
  },
  {
    id: uuidv4(),
    campaignName: 'Winter Gear Promo',
    status: 'OFF',
    keywords: ['winter', 'gear', 'clothing', 'sale'],
    bidAmount: 1,
    campaignFund: 6000,
    town: 'Wrocław',
    radius: 20,
  },
  {
    id: uuidv4(),
    campaignName: 'Tech Gadgets Sale',
    status: 'ON',
    keywords: ['tech', 'gadgets', 'electronics', 'sale'],
    bidAmount: 7,
    campaignFund: 12000,
    town: 'Poznań',
    radius: 40,
  },
  {
    id: uuidv4(),
    campaignName: 'Back to School',
    status: 'OFF',
    keywords: ['school', 'stationery', 'back to school', 'discount'],
    bidAmount: 5,
    campaignFund: 8000,
    town: 'Lublin',
    radius: 60,
  },
  {
    id: uuidv4(),
    campaignName: 'Spring Collection Launch',
    status: 'ON',
    keywords: ['spring', 'collection', 'fashion', 'launch'],
    bidAmount: 4,
    campaignFund: 11000,
    town: 'Szczecin',
    radius: 70,
  },
];

export const cities: string[] = [
  'Aleksandrów Kujawski',
  'Aleksandrowice',
  'Bartoszyce',
  'Bełchatów',
  'Będzin',
  'Biały Kamień',
  'Białystok',
  'Biłgoraj',
  'Bielsko-Biała',
  'Bolesławiec',
  'Bogucice',
  'Braniewo',
  'Brzeg',
  'Brodnica',
  'Bydgoszcz',
  'Bytom',
  'Czarnków',
  'Czeladź',
  'Człuchów',
  'Częstochowa',
  'Chełm',
  'Chełmno',
  'Chełmża',
  'Chojnów',
  'Chojnice',
  'Chorzów',
  'Chruszczów',
  'Cieszyn',
  'Dąb',
  'Dąbrowa Górnicza',
  'Dąbrówka Mała',
  'Dębica',
  'Długa Szlachecka',
  'Dzierżoniów',
  'Działdowo',
  'Ełk',
  'Elbląg',
  'Gdańsk',
  'Gdynia',
  'Giżycko',
  'Głogów',
  'Gliwice',
  'Gniezno',
  'Golub-Dobrzyń',
  'Gorlice',
  'Gorzów Wielkopolski',
  'Grajewo',
  'Grudziądz',
  'Halemba',
  'Iława',
  'Inowrocław',
  'Jasien',
  'Jawor',
  'Jodłówka',
  'Kalisz',
  'Katowice',
  'Kędzierzyn-Koźle',
  'Kętrzyn',
  'Kielce',
  'Knurów',
  'Koło',
  'Kołobrzeg',
  'Koszalin',
  'Koszutka',
  'Kościan',
  'Kościerzyna',
  'Kraśnik',
  'Kraków',
  'Krotoszyn',
  'Kwidzyn',
  'Legionowo',
  'Legnica',
  'Lębork',
  'Leszno',
  'Lidzbark Warmiński',
  'Libertów',
  'Lipno',
  'Lubań',
  'Lubartów',
  'Luboń',
  'Lubin',
  'Lublin',
  'Łańcut',
  'Łęczyca',
  'Łódź',
  'Łomianki',
  'Łowicz',
  'Malbork',
  'Marki',
  'Mielec',
  'Milanówek',
  'Mińsk Mazowiecki',
  'Mrągowo',
  'Mysłowice',
  'Nowa Sól',
  'Nowy Sącz',
  'Oleśnica',
  'Olsztyn',
  'Oława',
  'Opole',
  'Osowa',
  'Ostrów Wielkopolski',
  'Ostrołęka',
  'Ozorków',
  'Pabianice',
  'Piekary Śląskie',
  'Piastów',
  'Płock',
  'Płońsk',
  'Podgórze',
  'Poznań',
  'Pruszcz Gdański',
  'Pruszków',
  'Puck',
  'Radom',
  'Rawa Mazowiecka',
  'Raciąż',
  'Radzionków Nowy',
  'Rumia',
  'Rury',
  'Rybnik',
  'Rypin',
  'Rzeszów',
  'Sejny',
  'Siemianowice Śląskie',
  'Sidlice',
  'Skawina',
  'Słupca',
  'Sopot',
  'Sosnowiec',
  'Sochaczew',
  'Stargard Szczeciński',
  'Starachowice',
  'Starogard Gdański',
  'Suchanino',
  'Sulejówek',
  'Szczytno',
  'Szczecin',
  'Świdnik',
  'Świdnica',
  'Świętochłowice',
  'Tarnów',
  'Tczew',
  'Tomaszów Lubelski',
  'Tomaszów Mazowiecki',
  'Toruń',
  'Turek',
  'Tychy',
  'Ustka',
  'Wałbrzych',
  'Warsaw',
  'Wejherowo',
  'Włocławek',
  'Wołomin',
  'Wola Rzędzińska',
  'Wrocław',
  'Wąbrzeźno',
  'Wągrowiec',
  'Zabrze',
  'Zambrów',
  'Zamość',
  'Zawodzie',
  'Zbylitowska Góra',
  'Zduńska Wola',
  'Zgierz',
  'Zgłobice',
  'Zgorzelec',
  'Zielona Góra',
  'Złotoryja',
  'Złotów',
  'Żary',
  'Żyrardów',
];
